[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "immune feed penalty brother album tell chunk until faculty gate degree swamp idle camp maid ticket exile fiscal birth soda stereo tribe maple leopard"
